In [6]:
import pandas as pd

In [8]:
df.columns

Index(['PatientID', 'Split', 'DB', 'RTSTART', 'Geslacht', 'Leeftijd', 'Loctum',
       'Loctum2', 'Technique', 'Inplancode',
       ...
       'N1', 'N2', 'N3', 'Roken_Ja, in verleden', 'Roken_Ja, nog steeds',
       'Roken_Nee', 'Chemoradiation', 'Bioradiation',
       'Concurrent_Chemo_or_Bioradiation', 'Protons'],
      dtype='object', length=184)

In [7]:
path = '/home/macraedc/data/MT_dataset_with_all_structs.csv'

df = pd.read_csv(path, sep=';')
df

,PatientID,Split,DB,RTSTART,Geslacht,Leeftijd,Loctum,Loctum2,Technique,Inplancode,...,N1,N2,N3,"Roken_Ja, in verleden","Roken_Ja, nog steeds",Roken_Nee,Chemoradiation,Bioradiation,Concurrent_Chemo_or_Bioradiation,Protons
0,10125,train_val,REDCAP,2018-07-02,0,0.55,Palatum molle + uvula,Pharynx,VMAT,HH 35 6x-F,...,0,0,0,1,0,0,0,0,0,0
1,10152,train_val,REDCAP,2013-08-12,1,0.59,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,HH IMRT 35 5x PET_CT(CBCT),...,0,1,0,0,1,0,1,0,1,0
2,10279,train_val,CITOR143,2017-10-23,1,0.67,Supraglottisch,Larynx,VMAT,HH VMAT 35 5x CBCT,...,0,1,0,1,0,0,1,0,1,0
3,10348,test,CITOR750,2009-05-25,1,0.81,Glottisch,Larynx,3D-CRT,-1,...,0,0,0,0,0,1,0,0,0,0
4,10619,train_val,CITOR750,2012-08-13,1,0.64,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,-1,...,0,1,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1368,99777,train_val,RECAP,2023-04-12,1,0.71,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH 35 5pw-P,...,0,1,0,1,0,0,0,0,0,1
1369,99798,train_val,REDCAP,2019-07-24,1,0.71,Supraglottisch,Larynx,VMAT,HH 35 5x-F,...,0,1,0,1,0,0,0,0,0,0
1370,99820,train_val,CITOR750,2010-01-11,1,0.76,Hypopharynxachterwand (vanaf nivo vallecula),Pharynx,IMRT,-1,...,1,0,0,1,0,0,0,1,1,0
1371,99870,train_val,RECAP,2023-07-05,1,0.60,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH 35 5pw-P,...,0,1,0,1,0,0,0,0,0,1
1372,99917,train_val,RECAP,2022-02-09,0,0.58,Nasopharynx,Pharynx,Protons,HH-Primair-Standaard,...,0,0,0,1,0,0,0,0,0,1

In [14]:
df_protons = df[df['Protons'] == 0]
df_protons.to_csv('/home/macraedc/data/MT_dataset_photons_only.csv', sep=';', index=False)

In [3]:
endpoint_list = ['Aspiration_M06', 'Dysphagia_M06', 'Sticky_M06', 'Taste_M06', 'Xerostomia_M06']

df = df[~df[endpoint_list].eq(-1).any(axis=1)]

In [4]:
df

,PatientID,Split,DB,RTSTART,Geslacht,Leeftijd,Loctum,Loctum2,Technique,Inplancode,...,N1,N2,N3,"Roken_Ja, in verleden","Roken_Ja, nog steeds",Roken_Nee,Chemoradiation,Bioradiation,Concurrent_Chemo_or_Bioradiation,Protons
0,10125,train_val,REDCAP,2018-07-02,0,0.55,Palatum molle + uvula,Pharynx,VMAT,HH 35 6x-F,...,0,0,0,1,0,0,0,0,0,0
1,10152,train_val,REDCAP,2013-08-12,1,0.59,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,HH IMRT 35 5x PET_CT(CBCT),...,0,1,0,0,1,0,1,0,1,0
2,10279,train_val,CITOR143,2017-10-23,1,0.67,Supraglottisch,Larynx,VMAT,HH VMAT 35 5x CBCT,...,0,1,0,1,0,0,1,0,1,0
3,10348,test,CITOR750,2009-05-25,1,0.81,Glottisch,Larynx,3D-CRT,-1,...,0,0,0,0,0,1,0,0,0,0
4,10619,train_val,CITOR750,2012-08-13,1,0.64,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,-1,...,0,1,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1367,99666,train_val,REDCAP,2021-02-25,0,0.52,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH-Primair-Standaard,...,0,1,0,1,0,0,1,0,1,1
1368,99777,train_val,RECAP,2023-04-12,1,0.71,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH 35 5pw-P,...,0,1,0,1,0,0,0,0,0,1
1369,99798,train_val,REDCAP,2019-07-24,1,0.71,Supraglottisch,Larynx,VMAT,HH 35 5x-F,...,0,1,0,1,0,0,0,0,0,0
1370,99820,train_val,CITOR750,2010-01-11,1,0.76,Hypopharynxachterwand (vanaf nivo vallecula),Pharynx,IMRT,-1,...,1,0,0,1,0,0,0,1,1,0
1372,99917,train_val,RECAP,2022-02-09,0,0.58,Nasopharynx,Pharynx,Protons,HH-Primair-Standaard,...,0,0,0,1,0,0,0,0,0,1

In [5]:
output_dir = '/home/macraedc/data/MT_dataset_with_all_structs_no_missing.csv'
df.to_csv(output_dir, sep=';', index=False)