In [1]:
import pandas as pd

In [3]:
df_PRIMA = pd.read_csv(r"/home/macraedc/data/uncertainty_project/UQ_PRIMA_2025.csv", sep=';')
df_PRIMA

,PatientID,Split,DB,RTSTART,Geslacht,Leeftijd,Loctum,Loctum2,Technique,Inplancode,...,N3,"Roken_Ja, in verleden","Roken_Ja, nog steeds",Roken_Nee,Accelerated_RT,Conventional_RT,Chemoradiation,Bioradiation,Concurrent_Chemo_or_Bioradiation,Protons
0,64760,test,CITOR750,2015-05-18,1,0.68,Glottisch,Larynx,IMRT,-1,...,0,0,1,0,1,0,0,0,0,0
1,22457,test,REDCAP,2018-04-16,1,0.56,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,VMAT,HH 35 ARTFORCE Standaard,...,0,0,1,0,0,0,1,0,1,0
2,63402,train_val,CITOR750,2015-06-01,1,0.67,Palatum molle + uvula,Pharynx,IMRT,-1,...,0,0,1,0,0,1,1,0,1,0
3,11967,test,REDCAP,2018-07-30,1,0.51,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,VMAT,HH 35 5x-F,...,0,0,0,1,0,1,1,0,1,0
4,70434,test,CITOR750,2014-10-15,1,0.77,Glottisch,Larynx,IMRT,-1,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,24593,test,CITOR750,2015-04-20,1,0.75,Glottisch,Larynx,IMRT,-1,...,0,0,1,0,0,1,0,0,0,0
1201,44060,train_val,CITOR143,2017-04-17,1,0.75,Glottisch,Larynx,VMAT,HH VMAT 33 5x CBCT,...,0,1,0,0,0,1,0,0,0,0
1202,48345,test,CITOR750,2015-03-30,1,0.66,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,-1,...,0,1,0,0,0,1,1,0,1,0
1203,59800,test,CITOR750,2015-05-04,1,0.50,Glottisch,Larynx,VMAT,-1,...,0,1,0,0,1,0,0,0,0,0
1204,45438,train_val,REDCAP,2020-01-20,0,0.64,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,Protons,HH Protonen Basis met HerCT,...,0,1,0,0,1,0,0,0,0,1

In [5]:
df_no_larynx = df_PRIMA[(df_PRIMA['Split'] != 'train_val') | (df_PRIMA['Loctum2'] != 'Larynx')]
df_no_larynx.to_csv(r"/home/macraedc/data/uncertainty_project/UQ_PRIMA_2025_no_larynx_in_development_set.csv", sep=';', index=False)

In [6]:
df_no_pharynx = df_PRIMA[(df_PRIMA['Split'] != 'train_val') | (df_PRIMA['Loctum2'] != 'Pharynx')]
df_no_pharynx.to_csv(r"/home/macraedc/data/uncertainty_project/UQ_PRIMA_2025_no_pharynx_in_development_set.csv", sep=';', index=False)

In [8]:
df_no_pharynx

,PatientID,Split,DB,RTSTART,Geslacht,Leeftijd,Loctum,Loctum2,Technique,Inplancode,...,N3,"Roken_Ja, in verleden","Roken_Ja, nog steeds",Roken_Nee,Accelerated_RT,Conventional_RT,Chemoradiation,Bioradiation,Concurrent_Chemo_or_Bioradiation,Protons
0,64760,test,CITOR750,2015-05-18,1,0.68,Glottisch,Larynx,IMRT,-1,...,0,0,1,0,1,0,0,0,0,0
1,22457,test,REDCAP,2018-04-16,1,0.56,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,VMAT,HH 35 ARTFORCE Standaard,...,0,0,1,0,0,0,1,0,1,0
3,11967,test,REDCAP,2018-07-30,1,0.51,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,VMAT,HH 35 5x-F,...,0,0,0,1,0,1,1,0,1,0
4,70434,test,CITOR750,2014-10-15,1,0.77,Glottisch,Larynx,IMRT,-1,...,0,1,0,0,0,1,0,0,0,0
6,50682,test,CITOR750,2015-08-10,1,0.75,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,-1,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,53284,test,CITOR750,2015-04-15,1,0.59,Glottisch,Larynx,VMAT,-1,...,0,0,1,0,1,0,0,0,0,0
1200,24593,test,CITOR750,2015-04-20,1,0.75,Glottisch,Larynx,IMRT,-1,...,0,0,1,0,0,1,0,0,0,0
1201,44060,train_val,CITOR143,2017-04-17,1,0.75,Glottisch,Larynx,VMAT,HH VMAT 33 5x CBCT,...,0,1,0,0,0,1,0,0,0,0
1202,48345,test,CITOR750,2015-03-30,1,0.66,Tonsil + fossa + pharynxboog + glossotonsillai...,Pharynx,IMRT,-1,...,0,1,0,0,0,1,1,0,1,0
1203,59800,test,CITOR750,2015-05-04,1,0.50,Glottisch,Larynx,VMAT,-1,...,0,1,0,0,1,0,0,0,0,0